name: REQ)Content-editor

on: workflow_dispatch

jobs:
  build:
    name: Build APP
    runs-on: ubuntu-latest
    steps:
      - name: GIT checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - id: deploy
        name: Deploy APP to dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
            ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            dokku-host: ${{ secrets.HOSTNAME }}
            app-name: ${{ secrets.DEV_CONTENT_EDITOR_NAME }}
            git-push-flags: --force
